server:
  port: ${MONITORING_SERVICE_PORT}

eureka:
  instance:
    hostname: ${INSTANCE_HOST}
    prefer-ip-address: ${PREFER_IP_ADDRESS}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}


spring:
  data:
    mongodb:
      uri: ${MONGO_MONITORING}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}

  application:
    name: monitoring-service


grpc:
  server:
    port: 6661
  security:
    enabled: false
    negotiationType: PLAINTEXT
  client:
    instrument-service:
      address: ${GRPC_INSTRUMENT_SERVER_CALL}
      negotiationType: PLAINTEXT
    iam-service:
      address: ${GRPC_IAM_SERVER_CALL}
      negotiationType: plaintext

management:
  metrics:
    tags:
      environment: local
      application: instrument-service